const { DataTypes } = require("sequelize");

const sequelize = require("../sequelize");

const User = sequelize.define("users", {
    user_id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true,
        allowNull: false,
        _autoGenerated: true
    },
    username: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true
    },
    password: {
        type: DataTypes.STRING,
        allowNull: false
    },
    email: DataTypes.STRING,
    name: DataTypes.STRING,
    lastName: DataTypes.STRING,
    cpfCnpj: DataTypes.STRING,
    instagram: DataTypes.STRING,
    picture: DataTypes.STRING,
    dateCad: {
        type: DataTypes.DATE,
        defaultValue: DataTypes.NOW
    }
})

// Create table if not exists...
const init = async () => {
    await User.sync();
}

init ();

module.exports = User;